name: apk_icone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  splash_master: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/among.png

splash_master:
  color: '#083D77'
  image: 'assets/among.png'
  android_gravity: center

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/among.png'
